# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180817_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='archivo',
            field=models.FileField(blank=True, upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='img',
            field=models.ImageField(blank=True, upload_to='imagenes'),
        ),
    ]
